[versions]
kotlin = "1.9.23"
wire = "4.9.3"

[libraries]

wire-runtime = { module = "com.squareup.wire:wire-runtime", version.ref = "wire" }
wire-client = { module = "com.squareup.wire:wire-grpc-client", version.ref = "wire" }
wire-schema = { module = "com.squareup.wire:wire-schema", version.ref = "wire" }
wire-kotlin-generator = { module = "com.squareup.wire:wire-kotlin-generator", version.ref = "wire" }

gradle-plugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-plugin-wire = { group = "com.squareup.wire", name = "wire-gradle-plugin", version.ref = "wire" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
wire = { id = "com.squareup.wire", version.ref = "wire" }

[bundles]
